# Generated by Django 2.0.7 on 2020-03-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian_option', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('signature_dish', models.BooleanField(default=False)),
                ('spice_level', models.IntegerField(max_length=1)),
                ('pieces', models.IntegerField(max_length=1)),
            ],
        ),
    ]
