# Generated by Django 2.0.7 on 2020-03-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='spice_level',
            field=models.IntegerField(default=0),
        ),
    ]
