# Generated by Django 2.0.7 on 2020-03-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_dish_d_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='d_course',
            new_name='dish_course',
        ),
    ]
