# Generated by Django 2.0.7 on 2020-03-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.dish'),
        ),
    ]
