# Generated by Django 2.0.7 on 2020-03-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20200308_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(to='restaurant.Order'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=99999),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.Dish'),
        ),
    ]
