# Generated by Django 2.0.7 on 2020-04-29 10:39

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0003_auto_20200429_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 10, 39, 34, 245729, tzinfo=utc)),
        ),
    ]
