# Generated by Django 2.0.7 on 2020-04-29 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0004_auto_20200429_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 10, 40, 41, 623581, tzinfo=utc)),
        ),
    ]
