# Generated by Django 2.0.7 on 2020-05-02 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0005_auto_20200429_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 5, 7, 18, 99437, tzinfo=utc)),
        ),
    ]
