# Generated by Django 2.0.7 on 2020-05-02 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('localized_recurrence', '0004_auto_20161108_2151'),
        ('maketime', '0006_auto_20200502_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('event_description', models.TextField()),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localized_recurrence.LocalizedRecurrence')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 5, 29, 32, 129216, tzinfo=utc)),
        ),
    ]
