# Generated by Django 2.0.7 on 2020-05-02 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0007_auto_20200502_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 6, 14, 17, 190276, tzinfo=utc)),
        ),
    ]
