# Generated by Django 2.0.7 on 2020-05-03 01:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0008_auto_20200502_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringcalendarevent',
            name='recurrence',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 1, 11, 55, 476759, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='RecurringCalendarEvent',
        ),
    ]
