# Generated by Django 2.0.7 on 2020-05-03 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0009_auto_20200503_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 1, 26, 21, 503863, tzinfo=utc)),
        ),
    ]
