# Generated by Django 2.0.7 on 2020-05-03 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0010_auto_20200503_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('Yearly', 'YEARLY'), ('Monthly', 'MONTHLY'), ('Weekly', 'WEEKLY'), ('Daily', 'DAILY')], max_length=200)),
                ('dtstart', models.DateField(default=datetime.datetime(2020, 5, 3, 1, 50, 3, 835519, tzinfo=utc))),
                ('tzid', models.CharField(choices=[('Yearly', 'YEARLY'), ('Monthly', 'MONTHLY'), ('Weekly', 'WEEKLY'), ('Daily', 'DAILY')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 1, 50, 3, 831500, tzinfo=utc)),
        ),
    ]
