# Generated by Django 2.0.7 on 2020-05-03 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0011_auto_20200503_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='dtstart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
