# Generated by Django 2.0.7 on 2020-05-03 02:31

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0012_auto_20200503_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='bymonth',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='bymonthday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='bysetpos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='byweekday',
            field=models.CharField(blank=True, choices=[('RRule.MO', 'Monday'), ('RRule.TU', 'Tuesday'), ('RRule.WE', 'Wednesday'), ('RRule.TH', 'Thursday'), ('RRule.FR', 'Friday'), ('RRule.SA', 'Saturday'), ('RRule.SU', 'Sunday')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='byweekno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='byyearday',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='interval',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='until',
            field=models.DateField(default=datetime.date(2020, 12, 31)),
        ),
        migrations.AddField(
            model_name='recurrence',
            name='wkst',
            field=models.CharField(choices=[('RRule.MO', 'Monday'), ('RRule.TU', 'Tuesday'), ('RRule.WE', 'Wednesday'), ('RRule.TH', 'Thursday'), ('RRule.FR', 'Friday'), ('RRule.SA', 'Saturday'), ('RRule.SU', 'Sunday')], default='RRule.MO', max_length=200),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='frequency',
            field=models.CharField(choices=[('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily')], max_length=200),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='tzid',
            field=models.CharField(default=datetime.datetime(2020, 5, 3, 2, 31, 13, 214712, tzinfo=utc), max_length=200),
        ),
    ]
