# Generated by Django 2.0.7 on 2020-05-03 02:44

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0013_auto_20200503_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='dtstart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='tzid',
            field=models.CharField(default=datetime.datetime(2020, 5, 3, 2, 44, 20, 600742, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateTimeField(default=datetime.date(2020, 12, 31)),
        ),
    ]
