# Generated by Django 2.0.7 on 2020-05-03 02:46

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0014_auto_20200503_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='tzid',
            field=models.CharField(default=datetime.datetime(2020, 5, 3, 2, 46, 52, 808009, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateField(default=datetime.date(2020, 12, 31)),
        ),
    ]
