# Generated by Django 2.0.7 on 2020-05-03 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0016_auto_20200503_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='tzid',
            field=models.CharField(default=datetime.datetime(2020, 5, 3, 2, 51, 42, 911876, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 23, 59, 42, 911876)),
        ),
    ]
