# Generated by Django 2.0.7 on 2020-05-03 02:53

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0018_auto_20200503_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='tzid',
            field=models.CharField(default=datetime.datetime(2020, 5, 3, 2, 53, 39, 751420, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 23, 59, 59, 751420)),
        ),
    ]
