# Generated by Django 2.0.7 on 2020-05-03 20:28

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0021_auto_20200503_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='multibymonth',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=47, null=True),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 23, 59, 59, 253026)),
        ),
    ]
