# Generated by Django 2.0.7 on 2020-05-03 20:58

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0023_auto_20200503_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='byweekday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RRule.MO', 'Monday'), ('RRule.TU', 'Tuesday'), ('RRule.WE', 'Wednesday'), ('RRule.TH', 'Thursday'), ('RRule.FR', 'Friday'), ('RRule.SA', 'Saturday'), ('RRule.SU', 'Sunday')], max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 23, 59, 59, 972262)),
        ),
    ]
