# Generated by Django 2.0.7 on 2020-05-03 22:34

import datetime
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0026_auto_20200503_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrence',
            name='testbysetpos',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 23, 59, 59, 53461)),
        ),
    ]
