# Generated by Django 2.0.7 on 2020-05-05 23:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketime', '0029_auto_20200505_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrence',
            name='testbysetpos',
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='bymonthday',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^-?[-?\\d,]+$')]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='bysetpos',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^-?[-?\\d,]+$')]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='byweekno',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^-?[-?\\d,]+$')]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='byyearday',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^-?[-?\\d,]+$')]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 23, 59, 59, 984087)),
        ),
    ]
